### ISSUE TITLE
Slow simulation performance 

### ISSUE THREAD

**Issue by iwaniwaniwan012** [QianfengClarkShen/Tbps_CRC#4]
I have slow simulation performance, or if it expected?
Simulation software - QuestaSim 10.7c Linux
CRC Parameters - ByteEnabled version, bus width 512b, pipeline 1.
CPU is rather good Intel i7-9700K, 64GB Ram

**Comment by iwaniwaniwan012** [comment]
> Could you be more specific? How slow was it? How many clock cycles can you simulate every minute? Have you try other simulators?

Thanks for advice, tested in ModelSim 10.2c and it work rather fast.
In QuestaSim it simulates approx 100-150 clocks in minute

**Comment by iwaniwaniwan012** [comment]
> Could you be more specific? How slow was it? How many clock cycles can you simulate every minute? Have you try other simulators?

Thanks for advice, tested in ModelSim 10.2c and it work rather fast.
In QuestaSim it simulates approx 100-150 clocks in minute

**Comment by QianfengClarkShen** [comment]
I would assume there is a workaround for you, therefore I will close the issue as not planned. I do not have a QuestaSim license and I am not planning to support it in the foreseeable future.

**Comment by QianfengClarkShen** [comment]
I would assume there is a workaround for you, therefore I will close the issue as not planned. I do not have a QuestaSim license and I am not planning to support it in the foreseeable future.
